import { useEffect } from "react";

export default function RiskGraph() {
  useEffect(() => {
    window.Bokeh.embed.embed_item(data, "risk-graph");
  }, []);
  return <div className="bk-root" id="risk-graph"></div>;
}

const data = {
  target_id: null,
  root_id: "1187",
  doc: {
    defs: [],
    roots: {
      references: [
        {
          attributes: { axis: { id: "1197" }, ticker: null },
          id: "1200",
          type: "Grid",
        },
        {
          attributes: { axis: { id: "1201" }, dimension: 1, ticker: null },
          id: "1203",
          type: "Grid",
        },
        {
          attributes: {
            axis_label: "Risk factors",
            formatter: { id: "1230" },
            major_label_policy: { id: "1232" },
            ticker: { id: "1202" },
          },
          id: "1201",
          type: "CategoricalAxis",
        },
        {
          attributes: {
            fill_alpha: { value: 0.1 },
            fill_color: { field: "color" },
            height: { value: 0.8 },
            line_alpha: { value: 0.1 },
            line_color: { field: "color" },
            right: { field: "val" },
            y: { field: "rei" },
          },
          id: "1224",
          type: "HBar",
        },
        {
          attributes: {
            factors: [
              "Unsafe sex",
              "Other environmental risks",
              "Occupational risks",
              "Unsafe water, sanitation, and handwashing",
              "Suboptimal temperature",
              "Alcohol use",
              "Child and maternal malnutrition",
              "Impaired kidney function",
              "High LDL cholesterol",
              "High body-mass index",
              "High fasting plasma glucose",
              "Air pollution",
              "Dietary risks",
              "Tobacco",
              "High systolic blood pressure",
            ],
          },
          id: "1186",
          type: "FactorRange",
        },
        { attributes: {}, id: "1232", type: "AllLabels" },
        { attributes: { source: { id: "1185" } }, id: "1226", type: "CDSView" },
        {
          attributes: {
            fill_color: { field: "color" },
            height: { value: 0.8 },
            line_color: { field: "color" },
            right: { field: "val" },
            y: { field: "rei" },
          },
          id: "1223",
          type: "HBar",
        },
        {
          attributes: {
            data_source: { id: "1185" },
            glyph: { id: "1223" },
            hover_glyph: null,
            muted_glyph: null,
            nonselection_glyph: { id: "1224" },
            view: { id: "1226" },
          },
          id: "1225",
          type: "GlyphRenderer",
        },
        {
          attributes: {
            active_multi: null,
            tools: [
              { id: "1204" },
              { id: "1205" },
              { id: "1206" },
              { id: "1207" },
              { id: "1208" },
              { id: "1209" },
              { id: "1218" },
            ],
          },
          id: "1211",
          type: "Toolbar",
        },
        {
          attributes: {
            bottom_units: "screen",
            fill_alpha: 0.5,
            fill_color: "lightgrey",
            left_units: "screen",
            level: "overlay",
            line_alpha: 1.0,
            line_color: "black",
            line_dash: [4, 4],
            line_width: 2,
            right_units: "screen",
            syncable: false,
            top_units: "screen",
          },
          id: "1210",
          type: "BoxAnnotation",
        },
        { attributes: {}, id: "1234", type: "Selection" },
        {
          attributes: {
            axis_label: "Number of deaths",
            formatter: { id: "1220" },
            major_label_policy: { id: "1229" },
            ticker: { id: "1198" },
          },
          id: "1197",
          type: "LinearAxis",
        },
        { attributes: {}, id: "1204", type: "PanTool" },
        { attributes: {}, id: "1193", type: "LinearScale" },
        {
          attributes: {
            data: {
              color: [
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#FABF25",
                "#63146E",
                "#FABF25",
                "#FABF25",
                "#FABF25",
              ],
              index: [
                236540, 232632, 232626, 232628, 236542, 232640, 232636, 232644,
                232646, 232618, 232614, 232630, 232622, 232638, 232616,
              ],
              rei: [
                "Unsafe sex",
                "Other environmental risks",
                "Occupational risks",
                "Unsafe water, sanitation, and handwashing",
                "Suboptimal temperature",
                "Alcohol use",
                "Child and maternal malnutrition",
                "Impaired kidney function",
                "High LDL cholesterol",
                "High body-mass index",
                "High fasting plasma glucose",
                "Air pollution",
                "Dietary risks",
                "Tobacco",
                "High systolic blood pressure",
              ],
              val: {
                __ndarray__:
                  "mmNbyOx/7z8+bbt0jYjvP3mcOHcsh/M/XtHZU5yC+j/qaZ+PNU//P5qmi1gpiQNAkdGiPJ+AB0D9CpCx20oJQK0jyceClhFAxd6ZCNMTFEARdvxlbgEaQNSJ+X7crxpA1Bk03q3FH0Dz4Tei9GohQHMFjtnxsCVA",
                dtype: "float64",
                order: "little",
                shape: [15],
              },
            },
            selected: { id: "1234" },
            selection_policy: { id: "1233" },
          },
          id: "1185",
          type: "ColumnDataSource",
        },
        { attributes: {}, id: "1205", type: "WheelZoomTool" },
        { attributes: {}, id: "1230", type: "CategoricalTickFormatter" },
        {
          attributes: { format: "%f millions" },
          id: "1220",
          type: "PrintfTickFormatter",
        },
        {
          attributes: { overlay: { id: "1210" } },
          id: "1206",
          type: "BoxZoomTool",
        },
        {
          attributes: {
            text: "Number of deaths by risk factor globally in 2019",
          },
          id: "1188",
          type: "Title",
        },
        { attributes: {}, id: "1207", type: "SaveTool" },
        { attributes: {}, id: "1208", type: "ResetTool" },
        { attributes: {}, id: "1233", type: "UnionRenderers" },
        { attributes: {}, id: "1195", type: "CategoricalScale" },
        { attributes: {}, id: "1209", type: "HelpTool" },
        {
          attributes: {
            callback: null,
            tooltips: [["Number of deaths", "@val{0.00} millions"]],
          },
          id: "1218",
          type: "HoverTool",
        },
        { attributes: {}, id: "1190", type: "DataRange1d" },
        { attributes: {}, id: "1229", type: "AllLabels" },
        {
          attributes: {
            below: [{ id: "1197" }],
            center: [{ id: "1200" }, { id: "1203" }],
            height: 500,
            left: [{ id: "1201" }],
            renderers: [{ id: "1225" }],
            title: { id: "1188" },
            toolbar: { id: "1211" },
            width: 800,
            x_range: { id: "1190" },
            x_scale: { id: "1193" },
            y_range: { id: "1186" },
            y_scale: { id: "1195" },
          },
          id: "1187",
          subtype: "Figure",
          type: "Plot",
        },
        { attributes: {}, id: "1202", type: "CategoricalTicker" },
        { attributes: {}, id: "1198", type: "BasicTicker" },
      ],
      root_ids: ["1187"],
    },
    title: "",
    version: "2.3.3",
  },
};
