import { useEffect } from "react";

export default function TemperatureGraph() {
  useEffect(() => {
    window.Bokeh.embed.embed_item(data, "temperature-graph");
  }, []);
  return <div className="bk-root" id="temperature-graph"></div>;
}

const data = {
  target_id: null,
  root_id: "171397",
  doc: {
    defs: [],
    roots: {
      references: [
        {
          attributes: {
            below: [{ id: "171408" }],
            center: [{ id: "171411" }, { id: "171415" }, { id: "171457" }],
            extra_y_ranges: { co2: { id: "171461" } },
            height: 700,
            left: [{ id: "171412" }],
            renderers: [{ id: "171433" }, { id: "171466" }],
            right: [{ id: "171462" }],
            title: { id: "171398" },
            toolbar: { id: "171423" },
            x_range: { id: "171400" },
            x_scale: { id: "171404" },
            y_range: { id: "171402" },
            y_scale: { id: "171406" },
          },
          id: "171397",
          subtype: "Figure",
          type: "Plot",
        },
        { attributes: {}, id: "171400", type: "DataRange1d" },
        { attributes: { end: 2, start: -1 }, id: "171402", type: "Range1d" },
        { attributes: {}, id: "171469", type: "AllLabels" },
        {
          attributes: { overlay: { id: "171422" } },
          id: "171418",
          type: "BoxZoomTool",
        },
        { attributes: {}, id: "171417", type: "WheelZoomTool" },
        { attributes: {}, id: "171419", type: "SaveTool" },
        { attributes: {}, id: "171470", type: "BasicTicker" },
        {
          attributes: { days: [1, 4, 7, 10, 13, 16, 19, 22, 25, 28] },
          id: "171449",
          type: "DaysTicker",
        },
        { attributes: {}, id: "171420", type: "ResetTool" },
        {
          attributes: {
            line_alpha: 0.1,
            line_color: "#270B52",
            x: { field: "year" },
            y: { field: "co2" },
          },
          id: "171465",
          type: "Line",
        },
        { attributes: {}, id: "171404", type: "LinearScale" },
        { attributes: {}, id: "171421", type: "HelpTool" },
        { attributes: {}, id: "171406", type: "LinearScale" },
        {
          attributes: {
            formatter: { id: "171438" },
            major_label_policy: { id: "171436" },
            ticker: { id: "171409" },
          },
          id: "171408",
          type: "DatetimeAxis",
        },
        {
          attributes: {
            base: 60,
            mantissas: [1, 2, 5, 10, 15, 20, 30],
            max_interval: 1800000.0,
            min_interval: 1000.0,
            num_minor_ticks: 0,
          },
          id: "171446",
          type: "AdaptiveTicker",
        },
        { attributes: {}, id: "171456", type: "YearsTicker" },
        {
          attributes: { axis: { id: "171412" }, dimension: 1, ticker: null },
          id: "171415",
          type: "Grid",
        },
        {
          attributes: {
            num_minor_ticks: 5,
            tickers: [
              { id: "171445" },
              { id: "171446" },
              { id: "171447" },
              { id: "171448" },
              { id: "171449" },
              { id: "171450" },
              { id: "171451" },
              { id: "171452" },
              { id: "171453" },
              { id: "171454" },
              { id: "171455" },
              { id: "171456" },
            ],
          },
          id: "171409",
          type: "DatetimeTicker",
        },
        {
          attributes: {
            data_source: { id: "144829" },
            glyph: { id: "171464" },
            hover_glyph: null,
            muted_glyph: null,
            name: "co2",
            nonselection_glyph: { id: "171465" },
            view: { id: "171467" },
            y_range_name: "co2",
          },
          id: "171466",
          type: "GlyphRenderer",
        },
        {
          attributes: {
            data_source: { id: "144829" },
            glyph: { id: "171431" },
            hover_glyph: null,
            muted_glyph: null,
            name: "median_temperature",
            nonselection_glyph: { id: "171432" },
            view: { id: "171434" },
          },
          id: "171433",
          type: "GlyphRenderer",
        },
        {
          attributes: {
            base: 24,
            mantissas: [1, 2, 4, 6, 8, 12],
            max_interval: 43200000.0,
            min_interval: 3600000.0,
            num_minor_ticks: 0,
          },
          id: "171447",
          type: "AdaptiveTicker",
        },
        {
          attributes: { months: [0, 2, 4, 6, 8, 10] },
          id: "171453",
          type: "MonthsTicker",
        },
        {
          attributes: { axis: { id: "171408" }, ticker: null },
          id: "171411",
          type: "Grid",
        },
        {
          attributes: {
            label: { value: "CO2 emmision (millions of tonnes)" },
            renderers: [{ id: "171466" }],
          },
          id: "171493",
          type: "LegendItem",
        },
        { attributes: {}, id: "144875", type: "UnionRenderers" },
        {
          attributes: {
            data: {
              co2: {
                __ndarray__:
                  "6SYxCKycaED2KFyPwtloQBKDwMqh8WlAppvEILAma0CcxCCwcuRvQC2yne+nQnBA6SYxCKxUcUBOYhBYOX5xQJhuEoPAwnFAXrpJDALVckCDwMqhRap0QPYoXI/Cu3VA9P3UeOkgdkD2KFyPwp13QPp+arx0cXlAsHJoke0Ee0Coxks3id97QNejcD0K3X1AeekmMQisfkA1XrpJDEmAQJ7vp8ZLpIBAoBov3SSxgUDl0CLb+ZKDQDEIrBxay4RA5dAi2/l3g0AIrBxaZB6FQIGVQ4tsbIVAbxKDwMrYhUCTGARWDgOGQClcj8L1lodALbKd76etikDHSzeJQZOLQGZmZmZmH41APzVeukn4jkCBlUOLbFGPQGZmZmZmjY9AI9v5fuoFkEA1XrpJDNOQQMl2vp8aoZJA8KfGSzefkkBg5dAi20mUQOxRuB6FO5VAexSuR2FolUAzMzMzsyaVQClcj8J145VAtMh2vh81l0DTTWIQ2PaXQDm0yHY+GZlA+FPjpRt5mkC0yHa+n+ucQGZmZmbmgJ5ABoGVQwuDn0BqvHSTmCegQJZDi2wnoKFA8KfGS7fToUCNl24SQ/uiQArXo3C976NAWmQ734+KpkC+nxov3bClQCPb+X4qjqZAsHJokS2np0CBlUOL7BSoQIts5/upOKlAUI2XbtJIq0DfT42XrsCoQLByaJEtaqhAK4cW2U5aqkDLoUW2c4+rQB1aZDtfLqtAaJHtfL+Np0AEVg4tMmerQH9qvHQTCKhAcT0K1+M0qUD0/dR4KZqsQDVeuknMsKxA2/l+arwBrUB7FK5HYXqsQFYOLbLdGq9AYOXQIhv1rkCyne+nJp+wQFYOLbIdpq5ABoGVQ4tiq0C8dJMYRK6oQMUgsHLo/KlAiUFg5VBDrEAZBFYOLaitQOf7qfGSSrBAsp3vp+ZqsUDufD81PmOwQKAaL90kVrFAZDvfT+3xskAOLbKdL1+zQJqZmZm5S7NATDeJQUCfs0BaZDvfb/GzQHNoke28lLBAMQisHHoZskDD9ShcLwq0QArXo3AdGbVAfT81Xhp7tEBzaJHtPHO3QMdLN4nB67hAbef7qbFBuUB9PzVeuve5QA4tsp3vhbpARrbz/TQTvUB1kxgENvS+QBsv3SSG+b9AzczMzMxwwEB56SYxGEzBQDvfT413VcJABoGVQ7tkwkDwp8ZLBwvDQI2XbhLDD8RA/Knx0m0mxUD8qfHSnRrGQO58PzXuLMdAz/dT44Xpx0CgGi/d9DbJQAIrhxZJ48pAarx0k8gYzUAEVg4tIkXOQH9qvHSTrs9AnMQgsLKt0EB1kxgEZpzQQIcW2c6fpdBAwcqhRf6P0UCLbOf7oQ/SQAIrhxbxntJA1XjpJoEm00Dwp8ZLJwnTQNejcD26lNJAPQrXo/Bu0kBeukkMgo3SQM/3U+MtMtNA0SLb+V7X00Atsp3v5yLUQK5H4XqMxNRAx0s3iVmV1UBkO99PteHVQPp+arxkN9ZADAIrh4ax1kAtsp3vZwrWQOF6FK7fRNZAZDvfTyVt1kDb+X5qfOfWQN0kBoG9ltdAMzMzMyO710BOYhBYkaPXQLByaJG98ddAke18P42k2EB/arx0w9rYQGIQWDnMbdlAwcqhRa652kAxCKwc4vTbQD81Xrqx6NxAuB6F6+Hd3UBoke18b8HeQNv5fmpcUd9AnMQgsMLd3kCamZmZ6UfgQFCNl26O1OBAZmZmZsIT4UDNzMzMYDrhQARWDi3OWeFARrbz/QxV4UCcxCCwjk/hQA4tsp23iuFArkfhesTk4UC8dJMY0OvhQA==",
                dtype: "float64",
                order: "little",
                shape: [170],
              },
              country: [
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
                "World",
              ],
              index: [
                0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
                34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
                66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
                82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
                98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
                124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
                137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
                150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
                163, 164, 165, 166, 167, 168, 169,
              ],
              iso_code: [
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
                "OWID_WRL",
              ],
              median_temperature: {
                __ndarray__:
                  "rBxaZDvf17+BlUOLbOfLv8l2vp8aL82/nu+nxks30b9YObTIdr7Pv5zEILByaNG/tvP91Hjp1r8bL90kBoHdvxfZzvdT492/kxgEVg4t0r/ByqFFtvPVvz81XrpJDNq/+FPjpZvE4L+YbhKDwMrRvwRWDi2ynd+/QmDl0CLb0b+q8dJNYhDQvyUGgZVDi9S/EFg5tMh2zr/4U+Olm8TQv0SLbOf7qdG/cT0K16Nw1b91kxgEVg7Nv9v5fmq8dNO/WmQ730+N179I4XoUrkfZv/p+arx0k9i/MzMzMzMzs7/sUbgeheuhP3E9CtejcM2/dZMYBFYOzb+amZmZmZnJv90kBoGVQ8u/i2zn+6nx0r+TGARWDi3av0w3iUFg5di/sHJoke1817+Nl24Sg8Dav9nO91PjpdO/F9nO91Pjxb85tMh2vp/avx+F61G4HtW/H4XrUbge3b8Sg8DKoUXevz0K16NwPdq/9ihcj8L12L8CK4cW2c7Hv5HtfD81Xsq/ke18PzVe2r/l0CLb+X7Sv5ZDi2zn+8m/+n5qvHST0L/ufD81XrrZvw4tsp3vp96/pHA9Ctej4L9U46WbxCDYv+kmMQisHNK/w/UoXI/C3b8nMQisHFrgv05iEFg5tOC/XI/C9Shc37+cxCCwcmjhvyuHFtnO99u/iUFg5dAi278IrBxaZDvPvz81XrpJDMK/UI2XbhKD2L/ByqFFtvPdvx1aZDvfT9W/mpmZmZmZ0b8EVg4tsp3Pv1YOLbKd78e/hxbZzvdT079Ei2zn+6nRvzeJQWDl0NK/hetRuB6Fy7/ZzvdT46W7v+F6FK5H4cq/ke18PzVeyr9mZmZmZmbWv/Cnxks3icG/EoPAyqFFtr/wp8ZLN4nBv0a28/3UeNG/+FPjpZvEwL9iEFg5tMjGvzeJQWDl0MK/ObTIdr6fmr/6fmq8dJN4vzm0yHa+n6q/eekmMQisjD97FK5H4XqUP9nO91PjpZu//Knx0k1icL8730+Nl27CP5qZmZmZmZk/kxgEVg4tsr/b+X5qvHSjvyuHFtnO96O/i2zn+6nxsr++nxov3STGvzm0yHa+n6q/eekmMQisnD+iRbbz/dS4P1CNl24Sg8C/UrgehetRyL9KDAIrhxbRv3npJjEIrHy/WmQ730+Npz+cxCCwcmiRP0oMAiuHFqm/2/l+arx0oz956SYxCKyMP/p+arx0k6g/JQaBlUOLzL/sUbgehevBv5zEILByaLG/i2zn+6nxsr8hsHJoke28v/yp8dJNYqA/2c73U+Olm78CK4cW2c7Hv6RwPQrXo7C/WDm0yHa+rz8xCKwcWmTLv99PjZduEsO/DAIrhxbZzr+q8dJNYhCoP1g5tMh2vq+/yXa+nxovrT9aZDvfT423P+xRuB6F68E/ukkMAiuHhj+iRbbz/dTIP3npJjEIrIy/uB6F61G4nr8K16NwPQqnP/p+arx0k8g/8tJNYhBYyT9oke18PzW+P4ts5/up8dI/qMZLN4lB0D/hehSuR+G6P4ts5/up8cI/ObTIdr6fyj/NzMzMzMzUPwaBlUOLbMc/9ihcj8L12D9zaJHtfD/hPy/dJAaBldM/N4lBYOXQ0j/TTWIQWDncP1g5tMh2vt8/KVyPwvUo4D/P91PjpZvcP3E9CtejcOE//tR46SYx4D8GgZVDi2zfP0jhehSuR9k//tR46SYx4D/sUbgehevhPzMzMzMzM9s/FK5H4XoU3j+mm8QgsHLgP7pJDAIrh+I/0SLb+X5q6D8bL90kBoHpP0SLbOf7qeU/tMh2vp8a4z9aZDvfT43nPw==",
                dtype: "float64",
                order: "little",
                shape: [170],
              },
              year: {
                __ndarray__:
                  "AABgKIONi8IAAACfxVKLwgAAoBUIGIvCAABgWSHdisIAAADQY6KKwgAAoEamZ4rCAABAvegsisIAAAABAvKJwgAAoHdEt4nCAABA7oZ8icIAAOBkyUGJwgAAoKjiBonCAABAHyXMiMIAAOCVZ5GIwgAAgAyqVojCAABAUMMbiMIAAODGBeGHwgAAgD1IpofCAAAgtIprh8IAAOD3ozCHwgAAgG7m9YbCAAAg5Si7hsIAAMBba4CGwgAAgJ+ERYbCAAAgFscKhsIAAMCMCdCFwgAAYANMlYXCAAAgR2VahcIAAMC9px+FwgAAYDTq5ITCAAAAqyyqhMIAAMDuRW+EwgAAYGWINITCAAAA3Mr5g8IAAKBSDb+DwgAAYJYmhIPCAAAADWlJg8IAAKCDqw6DwgAAQPrt04LCAAAAPgeZgsIAAKC0SV6CwgAAQCuMI4LCAADgoc7ogcIAAKDl562BwgAAQFwqc4HCAADg0mw4gcIAAIBJr/2AwgAAQI3IwoDCAADgAwuIgMIAAIB6TU2AwgAAIPGPEoDCAACAz6Svf8IAAMC8KTp/wgAAAKquxH7CAABAlzNPfsIAAMAeZtl9wgAAAAzrY33CAABA+W/ufMIAAIDm9Hh8wgAAAG4nA3zCAABAW6yNe8IAAIBIMRh7wgAAwDW2onrCAABAvegsesIAAICqbbd5wgAAwJfyQXnCAAAAhXfMeMIAAIAMqlZ4wgAAwPku4XfCAAAA57Nrd8IAAEDUOPZ2wgAAwFtrgHbCAAAASfAKdsIAAEA2dZV1wgAAgCP6H3XCAAAAqyyqdMIAAECYsTR0wgAAgIU2v3PCAADAcrtJc8IAAED67dNywgAAgOdyXnLCAADA1PfoccIAAADCfHNxwgAAgEmv/XDCAADANjSIcMIAAAAkuRJwwgAAgCJ8Om/CAACAMeFObsIAAAAM62NtwgAAgOb0eGzCAAAAwf6Na8IAAADQY6JqwgAAgKptt2nCAAAAhXfMaMIAAIBfgeFnwgAAgG7m9WbCAAAASfAKZsIAAIAj+h9lwgAAAP4DNWTCAAAADWlJY8IAAIDncl5iwgAAAMJ8c2HCAACAnIaIYMIAAABX1zlfwgAAAAzrY13CAAAAwf6NW8IAAAB2ErhZwgAAAJTc4FfCAAAASfAKVsIAAAD+AzVUwgAAALMXX1LCAAAA0eGHUMIAAAAM62NNwgAAAHYSuEnCAAAA4DkMRsIAAAAczl1CwgAAAAzrYz3CAAAA4DkMNsIAAABoEWktwgAAALDEXh3CAAAAAAAAAAAAAACwxF4dQgAAALDEXi1CAAAA4DkMNkIAAAAM62M9QgAAABzOXUJCAAAAsqYJRkIAAAB2ErhJQgAAAAzrY01CAAAA0eGHUEIAAAAczl1SQgAAAP4DNVRCAAAASfAKVkIAAACU3OBXQgAAAN/ItllCAAAAwf6NW0IAAAAM62NdQgAAAFfXOV9CAAAA0eGHYEIAAADCfHNhQgAAgOdyXmJCAAAADWlJY0IAAIAyXzRkQgAAgCP6H2VCAAAASfAKZkIAAIBu5vVmQgAAAJTc4GdCAAAAhXfMaEIAAICqbbdpQgAAANBjompCAACA9VmNa0IAAIDm9HhsQgAAAAzrY21CAACAMeFObkIAAABX1zlvQgAAACS5EnBCAADANjSIcEIAAIBJr/1wQgAAQFwqc3FCAADA1PfocUIAAIDncl5yQgAAQPrt03JCAAAADWlJc0IAAICFNr9zQgAAQJixNHRCAAAAqyyqdEIAAMC9px91QgAAQDZ1lXVCAAAASfAKdkIAAMBba4B2Qg==",
                dtype: "float64",
                order: "little",
                shape: [170],
              },
            },
            selected: { id: "144876" },
            selection_policy: { id: "144875" },
          },
          id: "144829",
          type: "ColumnDataSource",
        },
        {
          attributes: {
            days: [
              1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
              20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
            ],
          },
          id: "171448",
          type: "DaysTicker",
        },
        {
          attributes: { source: { id: "144829" } },
          id: "171467",
          type: "CDSView",
        },
        { attributes: {}, id: "171413", type: "BasicTicker" },
        {
          attributes: {
            axis_label: "CO2 emmision in milions of tonnes",
            formatter: { id: "171471" },
            major_label_policy: { id: "171469" },
            ticker: { id: "171470" },
            y_range_name: "co2",
          },
          id: "171462",
          type: "LinearAxis",
        },
        {
          attributes: {
            axis_label: "Annual temperature anomalies median (\u00b0C)e",
            formatter: { id: "171441" },
            major_label_policy: { id: "171439" },
            ticker: { id: "171413" },
          },
          id: "171412",
          type: "LinearAxis",
        },
        { attributes: { end: 36702.503 }, id: "171461", type: "Range1d" },
        {
          attributes: {
            label: { value: "Annual temperature anomalies median (\u00b0C)" },
            renderers: [{ id: "171433" }],
          },
          id: "171458",
          type: "LegendItem",
        },
        { attributes: {}, id: "171438", type: "DatetimeTickFormatter" },
        { attributes: {}, id: "171441", type: "BasicTickFormatter" },
        {
          attributes: { months: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
          id: "171452",
          type: "MonthsTicker",
        },
        {
          attributes: {
            mantissas: [1, 2, 5],
            max_interval: 500.0,
            num_minor_ticks: 0,
          },
          id: "171445",
          type: "AdaptiveTicker",
        },
        {
          attributes: {
            callback: null,
            renderers: [{ id: "171433" }],
            tooltips: [
              [
                "Annual temperature anomalies median (\u00b0C)",
                "@median_temperature",
              ],
            ],
          },
          id: "171459",
          type: "HoverTool",
        },
        {
          attributes: {
            items: [{ id: "171458" }, { id: "171493" }],
            location: "top_left",
          },
          id: "171457",
          type: "Legend",
        },
        {
          attributes: {
            line_color: "#F57C15",
            x: { field: "year" },
            y: { field: "median_temperature" },
          },
          id: "171431",
          type: "Line",
        },
        {
          attributes: {
            line_color: "#270B52",
            x: { field: "year" },
            y: { field: "co2" },
          },
          id: "171464",
          type: "Line",
        },
        {
          attributes: { months: [0, 4, 8] },
          id: "171454",
          type: "MonthsTicker",
        },
        {
          attributes: {
            active_multi: null,
            tools: [
              { id: "171416" },
              { id: "171417" },
              { id: "171418" },
              { id: "171419" },
              { id: "171420" },
              { id: "171421" },
              { id: "171459" },
              { id: "171494" },
            ],
          },
          id: "171423",
          type: "Toolbar",
        },
        { attributes: {}, id: "171471", type: "BasicTickFormatter" },
        { attributes: {}, id: "171436", type: "AllLabels" },
        { attributes: {}, id: "144876", type: "Selection" },
        {
          attributes: {
            callback: null,
            renderers: [{ id: "171466" }],
            tooltips: [["CO2 emmisions in milions of tonnes", "@co2{0.00}"]],
          },
          id: "171494",
          type: "HoverTool",
        },
        {
          attributes: {
            bottom_units: "screen",
            fill_alpha: 0.5,
            fill_color: "lightgrey",
            left_units: "screen",
            level: "overlay",
            line_alpha: 1.0,
            line_color: "black",
            line_dash: [4, 4],
            line_width: 2,
            right_units: "screen",
            syncable: false,
            top_units: "screen",
          },
          id: "171422",
          type: "BoxAnnotation",
        },
        { attributes: { days: [1, 15] }, id: "171451", type: "DaysTicker" },
        {
          attributes: { source: { id: "144829" } },
          id: "171434",
          type: "CDSView",
        },
        { attributes: {}, id: "171416", type: "PanTool" },
        { attributes: {}, id: "171439", type: "AllLabels" },
        {
          attributes: {
            line_alpha: 0.1,
            line_color: "#F57C15",
            x: { field: "year" },
            y: { field: "median_temperature" },
          },
          id: "171432",
          type: "Line",
        },
        {
          attributes: { days: [1, 8, 15, 22] },
          id: "171450",
          type: "DaysTicker",
        },
        {
          attributes: {
            text: "Global annual temperature anomalies median vs global CO2 emmisions",
          },
          id: "171398",
          type: "Title",
        },
        { attributes: { months: [0, 6] }, id: "171455", type: "MonthsTicker" },
      ],
      root_ids: ["171397"],
    },
    title: "",
    version: "2.3.3",
  },
};
