import { useEffect } from "react";

export default function Top10Graph() {
  useEffect(() => {
    window.Bokeh.embed.embed_item(data, "top10-graph");
  }, []);
  return <div className="bk-root" id="top10-graph"></div>;
}

const data = {
  target_id: null,
  root_id: "15848",
  doc: {
    defs: [],
    roots: {
      references: [
        {
          attributes: {
            below: [{ id: "15859" }],
            center: [{ id: "15861" }, { id: "15865" }, { id: "15880" }],
            height: 500,
            left: [{ id: "15862" }],
            renderers: [{ id: "15885" }],
            title: { id: "15849" },
            toolbar: { id: "15873" },
            width: 800,
            x_range: { id: "15851" },
            x_scale: { id: "15855" },
            y_range: { id: "15853" },
            y_scale: { id: "15857" },
          },
          id: "15848",
          subtype: "Figure",
          type: "Plot",
        },
        { attributes: {}, id: "15892", type: "CategoricalTickFormatter" },
        {
          attributes: {
            text: "Top 10 CO2 emitting countries in 2020 with indication of global share of emissions",
          },
          id: "15849",
          type: "Title",
        },
        {
          attributes: {
            level: "glyph",
            source: { id: "15847" },
            text: { field: "perc" },
            x: { field: "country" },
            x_offset: { value: -14 },
            y: { field: "co2" },
          },
          id: "15880",
          type: "LabelSet",
        },
        { attributes: {}, id: "15867", type: "WheelZoomTool" },
        { attributes: {}, id: "15890", type: "AllLabels" },
        { attributes: {}, id: "15893", type: "AllLabels" },
        { attributes: {}, id: "15857", type: "LinearScale" },
        { attributes: {}, id: "15863", type: "BasicTicker" },
        { attributes: {}, id: "15889", type: "BasicTickFormatter" },
        {
          attributes: {
            factors: [
              "China",
              "United States",
              "India",
              "Russia",
              "Japan",
              "Iran",
              "Germany",
              "Saudi Arabia",
              "South Korea",
              "Indonesia",
            ],
          },
          id: "15851",
          type: "FactorRange",
        },
        { attributes: {}, id: "15871", type: "HelpTool" },
        {
          attributes: {
            fill_color: { field: "color" },
            line_color: { field: "color" },
            top: { field: "co2" },
            width: { value: 0.9 },
            x: { field: "country" },
          },
          id: "15883",
          type: "VBar",
        },
        {
          attributes: {
            active_multi: null,
            tools: [
              { id: "15866" },
              { id: "15867" },
              { id: "15868" },
              { id: "15869" },
              { id: "15870" },
              { id: "15871" },
            ],
          },
          id: "15873",
          type: "Toolbar",
        },
        { attributes: {}, id: "15855", type: "CategoricalScale" },
        { attributes: {}, id: "15869", type: "SaveTool" },
        { attributes: {}, id: "15853", type: "DataRange1d" },
        {
          attributes: { axis: { id: "15862" }, dimension: 1, ticker: null },
          id: "15865",
          type: "Grid",
        },
        { attributes: {}, id: "15860", type: "CategoricalTicker" },
        { attributes: {}, id: "15895", type: "UnionRenderers" },
        {
          attributes: {
            formatter: { id: "15892" },
            major_label_policy: { id: "15893" },
            ticker: { id: "15860" },
          },
          id: "15859",
          type: "CategoricalAxis",
        },
        {
          attributes: { axis: { id: "15859" }, ticker: null },
          id: "15861",
          type: "Grid",
        },
        {
          attributes: {
            data: {
              co2: {
                __ndarray__:
                  "x0s3ifHVxEA3iUFgxWiyQN0kBoGVE6NABoGVQ4ukmECamZmZGRuQQOF6FK5HSIdAFK5H4XoihEDy0k1iEIyDQKRwPQrXrIJAAAAAAABsgkA=",
                dtype: "float64",
                order: "little",
                shape: [10],
              },
              co2_per_capita: {
                __ndarray__:
                  "2c73U+OlHUBg5dAi23ksQOf7qfHSTfw/d76fGi+dJUDNzMzMzEwgQD0K16NwvSFAw/UoXI/CHkBkO99PjfcxQB1aZDvfTydAPQrXo3A9AUA=",
                dtype: "float64",
                order: "little",
                shape: [10],
              },
              color: [
                "#EA6428",
                "#FABB21",
                "#F3E056",
                "#F1ED70",
                "#F2F485",
                "#F4F78D",
                "#F5F891",
                "#F5F891",
                "#F6FA95",
                "#F6FA95",
              ],
              country: [
                "China",
                "United States",
                "India",
                "Russia",
                "Japan",
                "Iran",
                "Germany",
                "Saudi Arabia",
                "South Korea",
                "Indonesia",
              ],
              index: [
                4723, 24661, 11277, 19597, 12336, 11595, 9619, 20269, 21590,
                11409,
              ],
              iso_code: [
                "CHN",
                "USA",
                "IND",
                "RUS",
                "JPN",
                "IRN",
                "DEU",
                "SAU",
                "KOR",
                "IDN",
              ],
              perc: [
                "30.6%",
                "13.5%",
                "7.0%",
                "4.5%",
                "3.0%",
                "2.1%",
                "1.9%",
                "1.8%",
                "1.7%",
                "1.7%",
              ],
              year: [
                2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020,
              ],
            },
            selected: { id: "15894" },
            selection_policy: { id: "15895" },
          },
          id: "15847",
          type: "ColumnDataSource",
        },
        {
          attributes: {
            bottom_units: "screen",
            fill_alpha: 0.5,
            fill_color: "lightgrey",
            left_units: "screen",
            level: "overlay",
            line_alpha: 1.0,
            line_color: "black",
            line_dash: [4, 4],
            line_width: 2,
            right_units: "screen",
            syncable: false,
            top_units: "screen",
          },
          id: "15872",
          type: "BoxAnnotation",
        },
        {
          attributes: { source: { id: "15847" } },
          id: "15886",
          type: "CDSView",
        },
        {
          attributes: {
            data_source: { id: "15847" },
            glyph: { id: "15883" },
            hover_glyph: null,
            muted_glyph: null,
            nonselection_glyph: { id: "15884" },
            view: { id: "15886" },
          },
          id: "15885",
          type: "GlyphRenderer",
        },
        {
          attributes: {
            fill_alpha: { value: 0.1 },
            fill_color: { field: "color" },
            line_alpha: { value: 0.1 },
            line_color: { field: "color" },
            top: { field: "co2" },
            width: { value: 0.9 },
            x: { field: "country" },
          },
          id: "15884",
          type: "VBar",
        },
        {
          attributes: {
            axis_label: "Emissions in million tonnes",
            formatter: { id: "15889" },
            major_label_policy: { id: "15890" },
            ticker: { id: "15863" },
          },
          id: "15862",
          type: "LinearAxis",
        },
        { attributes: {}, id: "15894", type: "Selection" },
        { attributes: {}, id: "15870", type: "ResetTool" },
        {
          attributes: { overlay: { id: "15872" } },
          id: "15868",
          type: "BoxZoomTool",
        },
        { attributes: {}, id: "15866", type: "PanTool" },
      ],
      root_ids: ["15848"],
    },
    title: "",
    version: "2.3.3",
  },
};
